-- ============================================================
-- V1: Inisialisasi Schemas & Tabel Utama (auth & ods)
-- ============================================================

CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS ods;

-- 1. Tabel roles
CREATE TABLE IF NOT EXISTS auth.roles (
    id serial4 PRIMARY KEY,
    role_name varchar(50) NOT NULL UNIQUE,
    description varchar(255),
    created_by varchar(20) NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_by varchar(20),
    updated_at timestamp
);

-- 2. Tabel users
CREATE TABLE IF NOT EXISTS auth.users (
    id serial4 PRIMARY KEY,
    username varchar(50) NOT NULL UNIQUE,
    email varchar(150),
    password varchar(255),
    first_name varchar(100),
    last_name varchar(100),
    phone_number varchar(20),
    app_lang varchar(5) DEFAULT 'id',
    app_row_per_page int4 DEFAULT 10,
    status int4 DEFAULT 1 NOT NULL, -- 1=ACTIVE, 2=BLOCKED
    login_failed_count int4 DEFAULT 0 NOT NULL,
    created_by varchar(20) NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_by varchar(20),
    updated_at timestamp
);

-- 3. Junction table user <-> role
CREATE TABLE IF NOT EXISTS auth.user_roles (
    user_id int4 NOT NULL,
    role_id int4 NOT NULL,
    created_by varchar(20) NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT user_roles_role_fk FOREIGN KEY (role_id) REFERENCES auth.roles(id) ON DELETE CASCADE
);

-- 4. Tabel menu
CREATE TABLE IF NOT EXISTS auth.menu (
    id serial4 PRIMARY KEY,
    code varchar(10) NOT NULL UNIQUE,
    parent_code varchar(10),
    menu_key varchar(50) NOT NULL,
    path varchar(100) NOT NULL,
    icon varchar(50),
    sort_order int4 DEFAULT 0
);

-- 5. Junction table role <-> menu
CREATE TABLE IF NOT EXISTS auth.role_menus (
    role_id int4 NOT NULL,
    menu_id int4 NOT NULL,
    created_by varchar(20) NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL,
    CONSTRAINT role_menus_pkey PRIMARY KEY (role_id, menu_id),
    CONSTRAINT role_menus_role_fk FOREIGN KEY (role_id) REFERENCES auth.roles(id) ON DELETE CASCADE,
    CONSTRAINT role_menus_menu_fk FOREIGN KEY (menu_id) REFERENCES auth.menu(id) ON DELETE CASCADE
);

-- 6. Tabel setting_parameters
CREATE TABLE IF NOT EXISTS auth.setting_parameters (
    id serial4 PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    value varchar(255) NOT NULL,
    description varchar(255),
    created_by varchar(20) NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL,
    updated_by varchar(20),
    updated_at timestamp
);

-- 7. Tabel ods.all_features (Data agregasi & analitik nasabah)
CREATE TABLE IF NOT EXISTS ods.all_features (
    cust_no varchar(20) PRIMARY KEY,
    age numeric,
    tenure_months numeric,
    gender text,
    marital_status text,
    education text,
    occupation_type text,
    religion text,
    branch_code bigint,
    num_dependents numeric,
    income_range text,
    province text,
    city text,
    customer_status bigint DEFAULT 1,
    customer_open_date text,
    inactive_mark text,
    num_saving_accounts bigint,
    total_saving_balance bigint,
    has_saving smallint,
    days_since_last_debit_txn_raw text,
    days_since_last_credit_txn_raw text,
    num_deposito_accounts bigint,
    total_deposito_principal bigint,
    has_deposito smallint,
    auto_rollover_preference text,
    num_loans bigint,
    loan_amount bigint,
    loan_utilization bigint,
    loan_interest_rate numeric,
    no_days_overdue numeric,
    current_collectability text,
    has_loan smallint,
    loan_tenor_months numeric,
    loan_age_months numeric,
    remaining_tenor numeric,
    loan_purpose text,
    avg_balance_3m numeric,
    avg_balance_12m numeric,
    balance_volatility numeric,
    balance_trend_3m numeric,
    max_balance_last_12m numeric,
    min_balance_last_3m numeric,
    account_status_closure_date text,
    product_count_change_6m bigint,
    loan_interest_income bigint,
    loan_penalty_income bigint,
    deposit_interest_cost bigint,
    total_funding_depo bigint,
    saving_interest_cost bigint,
    total_funding_saving numeric,
    max_dpd_last_12m numeric,
    times_overdue_12m numeric,
    previous_loan_performance numeric,
    aum numeric,
    product_mix_category text,
    total_num_products numeric,
    has_ebanking smallint,
    days_since_last_login numeric,
    login_frequency_30d numeric,
    login_frequency_90d numeric,
    feature_diversity_score numeric,
    failed_auth_count numeric,
    device_change_flag smallint,
    collateral_type text,
    collateral_type_id numeric,
    collateral_value numeric,
    dependents_count numeric,
    employment_duration_months numeric,
    business_revenue numeric,
    loan_purpose_los text,
    disbursement_date text,
    pefindo_num_facilities numeric,
    pefindo_num_creditors numeric,
    pefindo_num_active numeric,
    pefindo_n_bank numeric,
    pefindo_n_multifinance numeric,
    pefindo_n_p2p numeric,
    pefindo_n_writeoff numeric,
    pefindo_n_negative numeric,
    pefindo_n_restructured numeric,
    pefindo_max_pastdue_days numeric,
    pefindo_worst_pastdue_days numeric,
    pefindo_total_outstanding numeric,
    pefindo_credit_history_months numeric,
    mgate_txn_count_30d numeric,
    mgate_txn_count_90d numeric,
    mgate_txn_count_180d numeric,
    mgate_avg_txn_amount_30d numeric,
    mgate_total_credit_30d numeric,
    mgate_total_debit_30d numeric,
    mgate_transfer_onus_count numeric,
    mgate_transfer_other_bank_count numeric,
    mgate_qris_count numeric,
    mgate_bill_payment_count numeric,
    mgate_ewallet_count numeric,
    mgate_pulsa_data_count numeric,
    mgate_cash_withdrawal_count numeric,
    mgate_cash_deposit_count numeric,
    mgate_days_since_last_txn numeric,
    mgate_total_txn_count numeric,
    igate_txn_count_30d numeric,
    igate_txn_count_90d numeric,
    igate_txn_count_180d numeric,
    igate_avg_txn_amount_30d numeric,
    igate_total_credit_30d numeric,
    igate_total_debit_30d numeric,
    igate_transfer_onus_count numeric,
    igate_transfer_other_bank_count numeric,
    igate_qris_count numeric,
    igate_bill_payment_count numeric,
    igate_ewallet_count numeric,
    igate_pulsa_data_count numeric,
    igate_cash_withdrawal_count numeric,
    igate_cash_deposit_count numeric,
    igate_days_since_last_txn numeric,
    igate_total_txn_count numeric,
    mgate_fee_total numeric,
    igate_fee_total numeric,
    srct24_txn_count_30d numeric,
    srct24_txn_count_60d numeric,
    srct24_txn_count_90d numeric,
    srct24_txn_count_180d numeric,
    srct24_txn_count_360d numeric,
    srct24_avg_txn_amount_30d numeric,
    srct24_total_credit_30d numeric,
    srct24_total_debit_30d numeric,
    srct24_net_flow_30d numeric,
    srct24_credit_debit_ratio numeric,
    srct24_days_since_any_txn numeric,
    srct24_transfer_in_count numeric,
    srct24_transfer_in_amount numeric,
    srct24_transfer_out_count numeric,
    srct24_transfer_out_amount numeric,
    srct24_largest_withdrawal_30d numeric,
    srct24_large_withdrawal_flag smallint,
    srct24_avg_monthly_inflow numeric,
    srct24_txn_dropped_50pct_flag smallint
);
